[<AutoOpen>]
module EpubFs.Types

open Giraffe.ViewEngine
open System
open System.IO

type RawInput =
    | Stream of Stream

type ContentInput =
    | Stream of Stream
    | Structured of XmlNode list

type NavInput =
    | Autogenerated
    | Stream of Stream

type CoverImage = {
    Input: RawInput
    MediaType: string }

type Metadata = {
    Id: string 
    Title: string
    Languages: string list
    ModifiedAt: DateTimeOffset option
    Creators: string list
    Source: string option }

type CssFile = {
    FileName: string
    Input: RawInput }

type Navigation =
    | Linear
    | NonLinear

type Xhtml = {
    Title: string
    FileName: string
    Navigation: Navigation option
    Input: ContentInput }

type Manifest = {
    CoverImage: CoverImage option
    NavXhtml: NavInput
    TitlePage: Xhtml
    ContentFiles: Xhtml list
    CssFiles: CssFile list }
