namespace EpubFs

open Giraffe.ViewEngine
open System
open System.IO

/// See: https://www.w3.org/TR/epub-33/#sec-smil-par-elem
type ParNode = {
    /// The fragment identifier (e.g., "#line1") referencing an element in the content file. The content file name is automatically prepended when writing the SMIL.
    TextFragmentReference: string
    ClipBegin: Choice<string, TimeSpan>
    ClipEnd: Choice<string, TimeSpan> }

type SmilInput =
    /// A raw SMIL file provided as a stream. Use this when you have a pre-built SMIL file.
    | Raw of Stream
    /// A list of XML nodes representing the head and body content of the SMIL file.
    | Structured of head: XmlNode list * body: XmlNode list
    /// A simplified representation using ParNode records. Each ParNode generates a `<par>` element with text and audio synchronization.
    | ParNodes of audioFileReference: string * parNodes: ParNode list

type ContentInput =
    /// A raw XHTML file provided as a stream. Use this when you have a pre-built XHTML file.
    | Raw of Stream
    /// A list of XML nodes representing the body content. The XHTML document structure (html, head, body) will be generated automatically.
    | Structured of body: XmlNode list

type NavInput =
    /// Automatically generate the navigation document (table of contents) from ContentFiles that have Navigation set.
    | Autogenerated
    /// A raw navigation XHTML file provided as a stream. Use this when you need custom navigation structure.
    | Raw of Stream

type CoverImage = {
    Input: Stream
    /// Media type of the image, such as "image/jpeg".
    MediaType: string
    /// File extension including the dot, such as ".jpg".
    Extension: string }

/// Media overlay metadata properties.
/// See: https://www.w3.org/TR/epub-33/#app-overlays-vocab
type MediaOverlayMetadata = {
    /// Total duration of the entire publication.
    TotalDuration: Choice<string, TimeSpan>
    /// CSS class for the currently playing element.
    ActiveClass: string option
    /// CSS class added to the root element during playback.
    PlaybackActiveClass: string option
    /// Name(s) of the narrator(s), optional.
    Narrators: string list }

type Metadata = {
    /// See: https://www.w3.org/TR/epub-33/#sec-opf-dcidentifier
    Id: string 
    /// See: https://www.w3.org/TR/epub-33/#sec-opf-dctitle
    Title: string
    /// At least one required, with the first one considered primary.
    /// See: https://www.w3.org/TR/epub-33/#sec-opf-dclanguage
    Languages: string list
    /// `None` defaults to DateTimeOffset.UtcNow
    /// See: https://www.w3.org/TR/epub-33/#last-modified-date
    ModifiedAt: DateTimeOffset option
    /// Optional.
    /// See: https://www.w3.org/TR/epub-33/#sec-opf-dccreator
    Creators: string list
    /// See: https://www.w3.org/TR/epub-33/#sec-opf-dcmes-optional-def
    Source: string option
    /// Book summary or blurb.
    /// See: https://www.w3.org/TR/epub-33/#sec-opf-dcmes-optional-def
    Description: string option
    /// Publisher name.
    /// See: https://www.w3.org/TR/epub-33/#sec-opf-dcmes-optional-def
    Publisher: string option
    /// Categories or tags for the publication. Optional.
    /// See: https://www.w3.org/TR/epub-33/#sec-opf-dcmes-optional-def
    Subjects: string list
    /// Copyright or rights statement. Optional.
    /// See: https://www.w3.org/TR/epub-33/#sec-opf-dcmes-optional-def
    Rights: string option
    /// Media overlay metadata. Required when the publication contains media overlays.
    /// See: https://www.w3.org/TR/epub-33/#sec-media-overlays
    MediaOverlay: MediaOverlayMetadata option }

type CssFile = {
    FileName: string
    Input: Stream }

type AudioFile = {
    MediaType: string
    FileName: string
    Input: Stream }

type SmilFile = {
    Input: SmilInput
    /// Duration of this media overlay. Used for media:duration metadata with refines.
    Duration: Choice<string, TimeSpan> }

/// https://www.w3.org/TR/epub-33/#attrdef-itemref-linear
type Navigation =
    /// Content that contributes to the primary reading order and has to be read sequentially.
    | Linear
    /// Auxiliary content that enhances or augments the primary content and can be accessed out of sequence.
    | NonLinear

/// Represents an XHTML content file in the EPUB.
type Xhtml = {
    Title: string
    FileName: string
    /// Indicates whether this file content contributes to the primary reading order and has to be read sequentially.
    /// Also, if the value is not `None` and the table of contents is to be autogenerated (`NavigationFile = Autogenerate`), this file will have an entry in the navigation document.
    /// See: https://www.w3.org/TR/epub-33/#sec-nav
    Navigation: Navigation option
    /// Optional SMIL file associated with this XHTML file for media overlays.
    /// If present, a corresponding `<item>` element for the SMIL file will be added to the manifest.
    /// See: https://www.w3.org/TR/epub-33/#sec-overlays-def
    Smil: SmilFile option
    Input: ContentInput }

/// Represents the manifest of files to be included in the EPUB.
type Manifest = {
    CoverImage: CoverImage option
    NavigationFile: NavInput
    TitlePage: Xhtml
    ContentFiles: Xhtml list
    CssFiles: CssFile list
    AudioFiles: AudioFile list }
